#include "oled.h"
#include "ssd1306.hpp"
#include "stm32f1xx_ll_bus.h"
#include "stm32f1xx_ll_gpio.h"
#include "c_i2c.hpp"
#include "conf.h"


void OLED_Init()
{
  LL_APB2_GRP1_EnableClock(APB2PER_ADDR2BIT(GPIO_PORT_OLED_SCL) | APB2PER_ADDR2BIT(GPIO_PORT_OLED_SDA));
  
  LL_GPIO_SetPinMode(GPIO_PORT_OLED_SCL, LL_GPIO_PIN_OLED_SCL, LL_GPIO_MODE_ALTERNATE);
  LL_GPIO_SetPinOutputType(GPIO_PORT_OLED_SCL, LL_GPIO_PIN_OLED_SCL, LL_GPIO_OUTPUT_OPENDRAIN);
  LL_GPIO_SetPinPull(GPIO_PORT_OLED_SCL, LL_GPIO_PIN_OLED_SCL, LL_GPIO_PULL_UP);
  LL_GPIO_SetPinSpeed(GPIO_PORT_OLED_SCL, LL_GPIO_PIN_OLED_SCL, LL_GPIO_SPEED_FREQ_LOW);
  
  LL_GPIO_SetPinMode(GPIO_PORT_OLED_SDA, LL_GPIO_PIN_OLED_SDA, LL_GPIO_MODE_ALTERNATE);
  LL_GPIO_SetPinOutputType(GPIO_PORT_OLED_SDA, LL_GPIO_PIN_OLED_SDA, LL_GPIO_OUTPUT_OPENDRAIN);
  LL_GPIO_SetPinPull(GPIO_PORT_OLED_SDA, LL_GPIO_PIN_OLED_SDA, LL_GPIO_PULL_UP);
  LL_GPIO_SetPinSpeed(GPIO_PORT_OLED_SDA, LL_GPIO_PIN_OLED_SDA, LL_GPIO_SPEED_FREQ_LOW);

  ENABLE_CLOCK_BY_ADDR(I2Cx_OLED);
}
